# Site settings
title: Test jatomas.com
email: ja.tomas@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jatomas.github.io" # the base hostname & protocol for your site

twitter_username: juanan169
github_username: jatomas

# Build settings
markdown: kramdown
